name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.18.0

      - name: Build library
        run: bazel build //apps/csv_fast:csv_fast

      - name: Test parser
        run: bazel test //tests:test_csv

